### ISSUE TITLE
关于MIUI息屏显示通知图标

### ISSUE THREAD

**Issue by MatrixLau** [ztc1997/MIUIAODNotificationIcon#1]
使用了无效，需要加什么应用吗，最新内测MIUI10，加了Android系统，系统UI了已经

**Comment by ztc1997** [comment]
请说明具体描述“无效”。

**Comment by MatrixLau** [comment]
@ztc1997 就是。。。无效啊，加入了太极阳，然后息屏没有其他通知图标

**Comment by ztc1997** [comment]
@MatrixLau 请说明机型和系统版本，确认通知级别以及是否允许锁屏显示。

**Comment by MatrixLau** [comment]
@ztc1997 MIX3 9.4.17 能给的权限都给了，要加什么应用吗？？

**Comment by ztc1997** [comment]
@MatrixLau 
1. 仅在开发版测试，不确定内测版的稳定性。
2. 只有在锁屏显示的通知会显示在aod，请在应用通知设置中检查是否允许在锁屏显示。

**Comment by MatrixLau** [comment]
@ztc1997 好的吧，第二个我有做到，那我还是放弃吧:joy:
